### ISSUE TITLE
ImportError: settings.test.py

### ISSUE THREAD

**Issue by gurvanrenault** [mrkipling/reddit-relationships-bot#3]
`   from settings import SETTINGS
ImportError: No module named settings`

- Rename settings.test.py  : settings.py

Version : Python 2.7.6

**Comment by mrkipling** [comment]
You need to make a copy of `settings.test.py`, call it `settings.py`, and fill in the information. This way `settings.py` can be in `.gitignore` (like it is currently) and you can push/pull changes without your API login info being included in the commit.
